config/routes.rb
Rails.application.routes.draw do
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index new create update show]
  resources :events, only: %i[index new create show]
  resources :invitations, only: %i[index new create show update]

  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :invitations, class_name: 'Invitation', foreign_key: 'attended_event_id'
  has_many :invitees, through: :invitations, source: :invitee

  scope :past, -> { where('event_date < ?', Date.today) }
  scope :upcoming, -> { where('event_date >= ?', Date.today) }

  validates :title, presence: true, length: { maximum: 50 }
  validates :event_date, presence: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invitee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'

  has_many :invitations, class_name: 'Invitation', foreign_key: 'invitee_id'
  has_many :attended_events, through: :invitations, source: :attended_event

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper

  def index
    @events = Event.all
    @past = Event.past
    @upcoming = Event.upcoming
  end

  def new
    @event = Event.new
  end

  def create
    user_id = session[:private_event_user_id]
    @user = User.find(user_id)
    @event = @user.created_events.create(event_params)

    if @event.save
      redirect_to event_path(@event)
    else
      flash.now
      render 'new'
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
    @users = User.all
    @session_id = session[:private_event_user_id]
    @confirmed_attendants_id = []
    @attendants = []

    @event&.invitations&.each do |invitation|
      @confirmed_attendants_id << invitation.invitee_id if invitation.confirmation == true
    end

    @users.each do |u|
      @confirmed_attendants_id.each do |ca|
        @attendants << u.name if u.id == ca
      end
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    @invitations = Invitation.all
  end

  def new
    @invitation = Invitation.new
    @user = session[:private_event_user_id]
  end

  def show
    @invitation = Invitation.find(params[:id])
    event_id = @invitation.attended_event_id
    @event = Event.find(event_id)
  end

  def create
    @invitation = Invitation.new(invitation_params)
    @event = @invitation.attended_event_id

    already_invited = Invitation.find_by_sql "
    SELECT id, invitee_id, attended_event_id FROM invitations
    WHERE invitee_id = #{@invitation.invitee_id} AND
    attended_event_id = #{@invitation.attended_event_id}"

    if !already_invited.empty?
      flash.now[:message] = 'User has already been invited'
      render 'new'
      nil
    else
      @invitation.save
      flash.notice = 'Invitation Successful !!'
      redirect_to events_path(@event)
    end
  end

  def update
    @invitation = Invitation.find(params[:id])

    @invitation.update_attribute(:confirmation, params[:confirmation] = true)
    @event = @invitation.attended_event_id

    redirect_to event_path(@event)
  end

  private

  def invitation_params
    params.require(:invitation).permit(:invitee_id, :attended_event_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new; end

  def create
    @user = User.find_by(id: params[:session][:private_event_user_id])

    if @user
      signin(@user.id)
      redirect_to user_path(@user.id)
    else
      flash.now[:message] = 'Incorrect'
      render 'new'
    end
  end

  def destroy
    logout

    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    user_invitations = @user.invitations

    @myevents = []
    @prev_event = []
    @upcoming_event = []
    @unconfirmed_invitations = []

    user_invitations.each do |invit|
      event_id = invit.attended_event_id
      event = Event.find(event_id)
      confirmed = invit.confirmation

      @prev_event << event if event.event_date.past? && confirmed
      @upcoming_event << event if !event.event_date.past? && confirmed
      @unconfirmed_invitations << invit if confirmed == false
    end

    @events = Event.all
    @events.each do |ev|
      @myevents << ev if ev.creator_id == session[:private_event_user_id]
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
      session[:private_event_user_id] = @user.id
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def past
    events = Event.all
    @prev_event = []

    events.each do |ev|
      @prev_event << ev if ev.event_date.past?
    end

    @prev_event
  end

  def upcoming
    events = Event.all
    @upcoming_event = []

    events.each do |ev|
      @upcoming_event << ev unless ev.event_date.past?
    end

    @upcoming_event
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_params
    params.require(:event).permit(:title, :event_date, :user_id)
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signin(user_id)
    session[:private_event_user_id] = user_id
  end

  def current_user
    @user = User.find_by(id: session[:private_event_user_id]) if session[:private_event_user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session[:private_event_user_id] = ''
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
  <h1>All events</h1>
  <% if current_user %>
    <%= link_to 'Create Event', new_event_path, class: 'btn' %>
  <% end %>


<ul>
  <h3>Upcoming Events:</h3>
  <% @upcoming.each do |e| %>
    <li>
      <h3> <%=link_to e.title, event_path(e) %></h3>
      <small><%= e.event_date %></small><br>
      <small>Created By:<%= e.creator.name %></small>
    </li>
  <% end %>
</ul>

<ul>
<h3>Past Events:</h3>
  <% @past.each do |e| %>
    <li>
      <h3> <%=link_to e.title, event_path(e) %></h3>
      <small><%= e.event_date %></small><br>
      <small>Created By:<%= e.creator.name %></small>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for @event, :url => events_path do |f| %>
  Title: <%= f.text_field :title %><br/>
  Event Date: <%= f.date_field :event_date %><br/>

  SUBMIT: <%= f.submit "Create Event"%>
<% end %>

app/views/events/show.html.erb
  <h1>
    <%= link_to 'Create Event', new_event_path %>
  </h1>

 <% if @event %>
  <h1>
    <%= @event.title  %>
  </h1>
  <p>
    Event date: <%= @event.event_date  %>
  </p>
  <small>
    Created By: <%= @event.creator.name %>
  </small>
<% else %>
  <p>No Events Created Yet</p>
<% end %>

<% if @session_id == @event.creator_id %>
  <p>
    <%= link_to 'Invite Users', new_invitation_path, class: 'btn' %>
  </p>
<% end %>

<h2>
  Attendants:
</h2>

<ul>
  <% @attendants.each do |name| %>
    <li>
      <%= name %>
    </li>
  <% end %>
</ul>

<p>
  <%= link_to '< All events', events_path %>
</p>

app/views/invitations/index.html.erb
<p><<<<<<<<<<<<<<<>>>>>>>>>>>>>>></p>

<%= link_to 'Invite A user to an Event', new_invitation_path, class: 'btn' %>

<p><<<<<<<<<<<<<<<>>>>>>>>>>>>>>></p>


<h4>All Invitations</h4>

<ul>
  <% @invitations.each do |iv| %>
    <li>
      <p>Invitation ID: <%=link_to iv.id, invitation_path(iv) %></p>
      <small>User Name: <%= iv.invitee_id %></small>
      <small>Event Title: <%= iv.attended_event_id %></small>
    </li>
  <% end %>
</ul>

app/views/invitations/new.html.erb
<%= flash[:message] %>

<h1>Invite User to Event</h1>

 <%= form_for :invitation, url:invitations_path do |f|%>

  <%= f.select :attended_event_id, Event.all.collect { |e| [ e.title, e.id ] if e.creator_id == @user }.select(&:present?), {:prompt => 'Select event'} %>
  <%= f.select :invitee_id, User.all.collect { |u| [ u.name, u.id ] if u.id != @user }.select(&:present?), {:prompt => 'Select invitee'} %>

  <%= f.submit "Invite User" %>
<% end %>

app/views/invitations/show.html.erb
<h1>Confirm Invitation</h1>

<h3>Event: <%=@event.title%></h3>
<small>Date: <%=@event.event_date%></small><br>
<br>
<%= form_for(:invitations, url: invitation_path, method: :patch ) do |f| %>
  <%= f.hidden_field :confirmation %>
  <%= f.submit 'Attend' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav>
    <div class="links"> 
      <p class = "navp"><%= link_to 'Events', events_path, class: 'off-white' %></p>
      <% if current_user %>
        <p class = "navp"> <%= link_to 'Create Event', new_event_path, class: 'off-white' %></p>
        <p class ="navp"> <%= link_to 'Profile', user_path(current_user), class: 'off-white' %></p>
      <% end %>
    </div>

    <div class="links">
      <% if current_user %>

        <%= form_for :session, url:logout_path do |f|%>
          <%= f.submit "Logout", method: :delete %>
        <% end %>

      <% else %>
        <p class = "navp"><%= link_to 'Sign Up', new_user_path, class: 'off-white' %></p>
        <p class = "navp"><%= link_to 'Sign In', signin_path, class: 'off-white' %></p>
      <% end %>
    </div>
  </nav>

  <body>
  <%= flash.notice %>

    <div class= "main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sing Up</h1>

<%= form_for (@user), :url => users_path do |f| %>

  Username: <%= f.text_field :name %><br/>
  Email: <%= f.email_field :email %><br/>

  SUBMIT: <%= f.submit "Create"%>
<% end %>

app/views/users/show.html.erb
<h1>User</h1>
<p>
  <strong> Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong> User Id:</strong>
  <%= @user.id %>
</p>

  <%= link_to 'Create Event', new_event_path, class: 'btn gree-highlight' %><br>
  <%= link_to 'Invite a User to an Event', new_invitation_path, class: 'btn' %>


   <ul>
      <strong>Events Created By Me:</strong>

      <% @myevents.each do |e| %>
        <li>
          <p><%= link_to e.title, event_path(e) %></p>
          <p><%= e.event_date %></p>
        </li>
        <% end %>
    </ul>

   <ul>
      <strong>Upcoming Events:</strong>
      <% @upcoming_event.each do |e| %>
        <li>
          <p><%= link_to e.title, event_path(e) %></p>
          <p><%= e.event_date %></p>
        </li>
        <% end %>
    </ul>

    <ul>
      <strong>Previous Events:</strong>
      <% @prev_event.each do |e| %>
        <li>
          <p><%= link_to e.title, event_path(e) %></p>
          <p><%= e.event_date %></p>
        </li>
        <% end %>
    </ul>

    <ul>
      <strong>Pending Invitations:</strong>
      <% @unconfirmed_invitations.each do |e| %>
        <li>
          <p>Invitation ID: <%= link_to e.id, event_path(e) %></p>
          <p><%#= e.event_date %></p>
          <p><%= link_to "Accept Invitation", invitation_path(e) %></p>
        </li>
        <% end %>
    </ul>